### ISSUE TITLE
Support multiple connections

### ISSUE THREAD

**Issue by mattKendon** [thephpleague/tactician-doctrine#19]
I've come across an occasion where I want to use this middleware in an app that has multiple Doctrine connections. 

At the moment the `ORM/TransactionMiddleware` takes an `EntityManager` instance, which will always be the default one. This means that when I have an entity that is managed under a different connection, I cannot use this middleware to ensure my command runs in a transaction. 

I believe a small change to the `ORM/TranasactionMiddleware` class would allow this middleware to support apps that use two or more connections in their Doctrine setup. 

```
 class TransactionMiddleware implements Middleware
{
    /**
     * @var ManagerRegistry
     */
    private $managerRegistry;

    /**
     * @param ManagerRegistry $managerRegistry
     */
    public function __construct(ManagerRegistry $managerRegistry)
    {
        $this->managerRegistry = $managerRegistry;
    }

    /**
     * Executes the given command and optionally returns a value
     *
     * @param object $command
     * @param callable $next
     * @return mixed
     * @throws Throwable
     * @throws Exception
     */
   public function execute($command, callable $next)
    {
        $connectionName = method_exists($command, 'getConnectionName') ?
            $command->getConnectionName() :
            $this->managerRegistry->getDefaultManagerName();

        $entityManager = $this->managerRegistry->getManager($connectionName);

        $entityManager->beginTransaction();

        try {
            $returnValue = $next($command);

            $entityManager->flush();
            $entityManager->commit();
        } catch (Exception $e) {
            $this->rollbackTransaction($entityManager);

            throw $e;
        } catch (Throwable $e) {
            $this->rollbackTransaction($entityManager);

            throw $e;
        }

        return $returnValue;
    }

    /**
     * Rollback the current transaction and close the entity manager when possible.
     *
     * @param EntityManagerInterface $entityManager
     */
    protected function rollbackTransaction(EntityManagerInterface $entityManager)
    {
        $entityManager->rollback();

        $connection = $entityManager->getConnection();
        if (!$connection->isTransactionActive() || $connection->isRollbackOnly()) {
            $entityManager->close();
        }
    }
}
```

This above example doesn't cover the case where two connections are being used in the same command, but it could certainly be extended to support that. 

Additionally an interface could be created that would define the `getConnectionName` that could be implemented by the command to improve the specificity of the if statement.

```
$connectionName = $command instanceof NonDefaultConnectionCommand ?
            $command->getConnectionName() :
            $this->managerRegistry->getDefaultManagerName();
```

Thanks for the great package, by the way.

**Comment by rosstuck** [comment]
Hi Matthew, 

Thanks for opening the issue and giving such great details!

After giving it some thought, I feel this solution is probably a bit too specific to your use case to add it to the package here. The goal with tactician-doctrine is just to provide the simplest 80% use-case middleware off-the-shelf for folks. For specific cases, Tactician provides the middleware solution (which you've correctly used here!) and probably belongs best within your app itself. 

Alternately, just curious: f you have a set of commands that are different enough to use segregated databases, would it be possible to use two separate command bus instances, rather than encode the DB connection name in multiple places? I'm just always trying to learn more about how folks use Tactician in practice. :)

I'll close this issue for now but feel free to re-open if you feel I've missed something. Thanks again, I really do appreciate your feedback and for writing such a good ticket!
